//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexOneVS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Queue
    {
        public int ID { get; set; }
        public string IDforAPI { get; set; }
        public string Type { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UserID { get; set; }
        public string ImagePath { get; set; }
        public string ItemName { get; set; }
        public bool Watched { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
